***Sorting***

In [2]:
import numpy as np

In [3]:
n1 = np.array([2,5,8,1,6,9,5,7])
print(np.sort(n1))
#default axis is -1 -->axis = -1 same result will get without giving axis

[1 2 5 5 6 7 8 9]


In [ ]:
n2 = np.array([[5,2,3],[4,9,1]])
print(np.sort(n2))

[[2 3 5]
 [1 4 9]]


In [ ]:
# axis = 0 Column
# axis = 1 Row
#Column wise it sorted
print(np.sort(n2,axis=0))

[[4 2 1]
 [5 9 3]]


***Reshaping and Array Conversions***

In [ ]:
#n1 = np.array([2,5,8,1,6,9,5,7])
n3 = n1.reshape(4,2) # 4-row 2-column
print(n3)

[[2 5]
 [8 1]
 [6 9]
 [5 7]]


In [ ]:
n4 = n1.reshape(2,4)
print(n4)

[[2 5 8 1]
 [6 9 5 7]]


In [ ]:
#Joining Two arrays
n5 = np.arange(4)
print(n5)
n6 = np.arange(5,9)
print(n6)
n7 = np.concatenate((n5,n6))
print(n7)

[0 1 2 3]
[5 6 7 8]
[0 1 2 3 5 6 7 8]


In [ ]:
# Converting 1D into 2D

n9 = n1[:,np.newaxis]
print(n9)
n10 = n1[np.newaxis,:]
print(n10)

[[2]
 [5]
 [8]
 [1]
 [6]
 [9]
 [5]
 [7]]
[[2 5 8 1 6 9 5 7]]


In [ ]:
n9.ndim


2

In [ ]:
n10.ndim

2

In [7]:
n11 = np.arange(10)
print(n11)


[0 1 2 3 4 5 6 7 8 9]


In [17]:
# expanding_dimension
n12 = np.expand_dims(n11,axis = 1)
print(n12)
n13 = np.expand_dims(n11,axis = 0)
print(n13)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[0 1 2 3 4 5 6 7 8 9]]


In [12]:
n12.shape

(10, 1)

In [26]:
n15 = np.arange(21,30).reshape(1,3,3)
print(n15)

[[[21 22 23]
  [24 25 26]
  [27 28 29]]]


***Indexing and Slicing***

In [29]:
n16 = n15>=26
print(n16)

[[[False False False]
  [False False  True]
  [ True  True  True]]]


In [34]:
n17 = n15<25
print(n17)
print(n15[n15<25])
print(n15[(n15<25)&(n15>21)])

[[[ True  True  True]
  [ True False False]
  [False False False]]]
[21 22 23 24]
[22 23 24]


In [35]:
print(np.nonzero(n15))

(array([0, 0, 0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))


In [42]:
n18 = np.arange(10,20)
print(n18)
print(n18[3:7])
print(n18[3:7:2])  #2 - step size

[10 11 12 13 14 15 16 17 18 19]
[13 14 15 16]
[13 15]


***Stack and Split***

In [44]:
#Hortizontal Stack Joining
n19 = np.array ([[1,2],[3,4]])
n20 = np.array([[5,6],[7,8]])
n21 = np.hstack((n19,n20))
print(n21)

[[1 2 5 6]
 [3 4 7 8]]


In [45]:
#Vertical Stack Joining
n19 = np.array ([[1,2],[3,4]])
n20 = np.array([[5,6],[7,8]])
n21 = np.vstack((n19,n20))
print(n21)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [59]:
n20 = np.arange(20)
print(n20)
print(np.hsplit(n20,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19])]


***Copy***

In [60]:
#Shallow copy
n21 = n20
n20[2] = 44
print(n21)
print(n20)

[ 0  1 44  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1 44  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [63]:
#Deep copy --> if we change in one array it will not change in another array
n22 = n20.copy()
n20[1] = 55
print(n22)
print(n20)

[ 0  1 44  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0 55 44  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


***Math and Random***

In [67]:
n23 = np.arange(0,6)
n24 = np.arange(6,12)
print(n23)
print(n24)
print(n23+n24)
print(n23-n24)
print(n23*n24)
print(n23/n24)
print(n23%n24)
print(n23.sum())
print(n23.min())
print(n23.max())
print(n23.mean())
print(n23.std())

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[ 6  8 10 12 14 16]
[-6 -6 -6 -6 -6 -6]
[ 0  7 16 27 40 55]
[0.         0.14285714 0.25       0.33333333 0.4        0.45454545]
[0 1 2 3 4 5]
15
0
5
2.5
1.707825127659933


In [68]:
np.random.rand(3,3)

array([[0.90792501, 0.88558271, 0.62378596],
       [0.02851878, 0.66125882, 0.51389701],
       [0.31344915, 0.73970896, 0.33224877]])

In [69]:
np.random.randint(100,size=(4,2))

array([[81, 16],
       [ 8,  4],
       [89, 62],
       [ 8, 13]])