In [ ]:
import numpy as np

# Create an array
data = np.array([10, 20, 30, 40, 50])

# Calculate the average
average = np.mean(data)

print("Average:", average)


Average: 30.0


In [ ]:
import numpy as np

T = np.array([[11, 12, 5, 2], [15, 6, 10, 7],
 [10, 8, 12, 5], [12, 15, 8, 6]])

# Calculate row-wise averages
row_averages = np.mean(T, axis=1)

# Calculate column-wise averages
column_averages = np.mean(T, axis=0)

print("Row-wise averages:", row_averages)
print("Column-wise averages:", column_averages)


Row-wise averages: [ 7.5   9.5   8.75 10.25]
Column-wise averages: [12.   10.25  8.75  5.  ]


In [ ]:
import numpy as np

data = [[[ '1', '1', '1'], ['1', '1', '1'], ['1', '1', '1']],
        [['1', '1', '1'], ['1', '1', '1'], ['1', '1', '1']],
        [['1', '1', '1'], ['1', '1', '1'], ['1', '1', '1']],
        [['2', '2', '2'], ['2', '2', '2'], ['2', '2', '2']],
        [['2', '2', '2'], ['2', '2', '2'], ['2', '2', '2']],
        [['2', '2', '2'], ['2', '2', '2'], ['2', '2', '2']]]

# Convert the nested list structure into a NumPy array
arr = np.array(data, dtype=int)

# Calculate the average along the specified axis
average1 = np.mean(arr, axis=0)
average2 = np.mean(arr, axis=1)
average3 = np.mean(arr, axis=2)

print("Average along first axis:\n", average1)
print("Average along second axis:\n", average2)
print("Average along third axis:\n", average3)


Average along first axis:
 [[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]
Average along second axis:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
Average along third axis:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [ ]:
import numpy as np

data = [[[ '1', '1', '1'], ['1', '1', '1'], ['1', '1', '1']],
        [['1', '1', '1'], ['1', '1', '1'], ['1', '1', '1']],
        [['1', '1', '1'], ['1', '1', '1'], ['1', '1', '1']],
        [['2', '2', '2'], ['2', '2', '2'], ['2', '2', '2']],
        [['2', '2', '2'], ['2', '2', '2'], ['2', '2', '2']],
        [['2', '2', '2'], ['2', '2', '2'], ['2', '2', '2']]]

# Convert the nested list structure into a NumPy array with integer data type
array = np.array(data, dtype=int)

# Calculate row-wise averages for each sub-matrix
row_averages = np.mean(array, axis=2)

# Calculate column-wise averages for each sub-matrix
column_averages = np.mean(array, axis=1)

print("Row-wise averages for each sub-matrix:\n", row_averages)
print("Column-wise averages for each sub-matrix:\n", column_averages)


Row-wise averages for each sub-matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
Column-wise averages for each sub-matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [ ]:
Data = [[[4, 2, 5, 3]],
        [[6, 3, 8, 3]],
        [[1, 3, 9, 7]],
        [[6, 8, 4, 7]],
        [[6, 5, 6, 4]],
        [[4, 8, 5, 4]]]
import numpy as np

# Convert the nested list structure into a NumPy array
array = np.array(Data)

# Calculate column-wise averages
column_averages = np.mean(array, axis=0)

print("Column-wise averages:\n", column_averages)


Column-wise averages:
 [[4.5        4.83333333 6.16666667 4.66666667]]


In [ ]:
import numpy as np

Data = [[[4, 2, 5, 3]],
        [[6, 3, 8, 3]],
        [[1, 3, 9, 7]],
        [[6, 8, 4, 7]],
        [[6, 5, 6, 4]],
        [[4, 8, 5, 4]]]

# Convert the nested list structure into a NumPy array
array = np.array(Data)

# Calculate column-wise averages
column_averages = np.mean(array, axis=0)
column_averages = np.mean(array, axis=1)
# Index the specific column average
column_index = 1  # Change this to the desired column index
specific_column_average = column_averages[1, column_index]

print(f"Average of column {column_index}:", specific_column_average)


Average of column 1: 3.0


In [ ]:
import numpy as np

Data = [[[4, 2, 5, 3]],
        [[6, 3, 8, 3]],
        [[1, 3, 9, 7]],
        [[6, 8, 4, 7]],
        [[6, 5, 6, 4]],
        [[4, 8, 5, 4]]]

# Convert the nested list structure into a NumPy array
array = np.array(Data)

# Calculate column-wise averages
column_averages = np.mean(array, axis=0)

# Index the second column average (index 1)
second_column_average = column_averages[0, 1]

print("Average of the second column:", second_column_average)


Average of the second column: 4.833333333333333


In [ ]:
import numpy as np

Data = [[[4, 2, 5, 3]],
        [[6, 3, 8, 3]],
        [[1, 3, 9, 7]],
        [[6, 8, 4, 7]],
        [[6, 5, 6, 4]],
        [[4, 8, 5, 4]]]

# Convert the nested list structure into a NumPy array
array = np.array(Data)

# Calculate column-wise averages
column_averages = np.mean(array, axis=0)

# Index the third column average (index 2)
third_column_average = column_averages[0, 2]

# Convert the average to a percentage
third_column_average_percent = third_column_average * 100

print("Average of the third column as a percentage:", third_column_average_percent)


Average of the third column as a percentage: 616.6666666666667


In [ ]:
import numpy as np

Data = [[[4, 2, 5, 3]],
        [[6, 3, 8, 3]],
        [[1, 3, 9, 7]],
        [[6, 8, 4, 7]],
        [[6, 5, 6, 4]],
        [[4, 8, 5, 4]]]

# Convert the nested list structure into a NumPy array
array = np.array(Data)

# Calculate column-wise averages
column_averages = np.mean(array, axis=0)

# Index the third column average (index 2)
third_column_average = column_averages[0, 2]

# Convert the average to a percentage and format as a string
third_column_average_percent = "{:.1f}%".format(third_column_average * 100)

print("Average of the third column as a percentage:", third_column_average_percent)


Average of the third column as a percentage: 616.7%


In [ ]:
import numpy as np

Data = [[[4, 2, 5, 3]],
        [[6, 3, 8, 3]],
        [[1, 3, 9, 7]],
        [[6, 8, 4, 7]],
        [[6, 5, 6, 4]],
        [[4, 8, 5, 4]]]

# Convert the nested list structure into a NumPy array
array = np.array(Data)

# Calculate column-wise averages
column_averages = np.mean(array, axis=0)

# Index the third column average (index 2)
third_column_average = column_averages[0, 2]

print("Average of the third column:", third_column_average)

# Calculate the average percentage
total_average = np.mean(array)
average_percentage = (third_column_average / total_average) * 100

print("Average percentage of the third column:", average_percentage)


Average of the third column: 6.166666666666667
Average percentage of the third column: 122.31404958677685


In [ ]:
import numpy as np

Data = [[[4, 2, 5, 3]],
        [[6, 3, 8, 3]],
        [[1, 3, 9, 7]],
        [[6, 8, 4, 7]],
        [[6, 5, 6, 4]],
        [[4, 8, 5, 4]]]

# Convert the nested list structure into a NumPy array
array = np.array(Data)

# Calculate the sum of all values
total_sum = np.sum(array)

print("Sum of all values:", total_sum)


Sum of all values: 121


In [ ]:
import numpy as np

Data = [[[4, 2, 5, 3]],
        [[6, 3, 8, 3]],
        [[1, 3, 9, 7]],
        [[6, 8, 4, 7]],
        [[6, 5, 6, 4]],
        [[4, 8, 5, 4]]]

# Convert the nested list structure into a NumPy array
array = np.array(Data)

# Extract the third column (index 2)
third_column = array[:, :, 2]

# Calculate the sum of values in the third column
total_average = np.sum(third_column)

print("Sum of values in the third column:", total_average)


Sum of values in the third column: 37


In [ ]:
import numpy as np

Data = [[[4, 2, 5, 3]],
        [[6, 3, 8, 3]],
        [[1, 3, 9, 7]],
        [[6, 8, 4, 7]],
        [[6, 5, 6, 4]],
        [[4, 8, 5, 4]]]

# Convert the nested list structure into a NumPy array
array = np.array(Data)

# Calculate column-wise averages
column_averages = np.mean(array, axis=0)

# Index the third column average (index 2)
third_column_average = column_averages[0, 2]

# Calculate the sum of values in the third column
third_column_sum = np.sum(array[:, :, 2])

# Calculate the total average of the entire array
total_average = np.mean(array[:, :, 2])

# Calculate the average percentage
average_percentage = (third_column_average / third_column_sum ) * 100

print("Average of the third column:", third_column_average)
print("Sum of values in the third column:", third_column_sum)
print("Average percentage:", average_percentage)


Average of the third column: 6.166666666666667
Sum of values in the third column: 37
Average percentage: 16.666666666666668
