In [16]:
import numpy as np
np.__version__

'1.25.2'

In [17]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [19]:
np.ones((3,3),dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [20]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [22]:
arr1.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
arr1.reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
arr[arr%2==1]

array([-1, -1, -1, -1, -1])

In [25]:
a = np.arange(10)
b = np.repeat(1,10)
b

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [26]:
np.concatenate([a,b])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
a = np.array([1,2,3])

In [28]:
np.r_[np.repeat(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [29]:
np.r_[np.tile(a,3)]

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [30]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [31]:
np.setdiff1d(a,b)

array([1, 3, 5, 6])

In [32]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)