# *What is List?*

List used to Store collection of elements

Dynamic size: Lists can grow and shrink in size dynamically.

Heterogeneous elements: Lists can contain elements of different data types.

Built-in methods: Lists have many built-in methods for manipulation (e.g., append(), remove(), sort()).








In [1]:
my_list = [1, 2, 'a', 3.5, True]

my_list.append('new_item')

print(my_list)




[1, 2, 'a', 3.5, True, 'new_item']


#***Why we need Array, we already have a list?***

#*What is Array?*

Fixed size: Arrays have a fixed size and require explicit resizing.

Homogeneous elements: Arrays typically contain elements of the same data type.

Efficient memory usage: Arrays are more memory efficient for large datasets of the same type.

Requires import: Arrays are available in Python through the array module or libraries like numpy.





**Memory Allocation in Array:**

 Arrays allocate memory in a contiguous block. This means that all elements are stored next to each other in memory.

**Memory Allocation in List:**

each element of the list is a reference (or pointer) to an object stored somewhere in memory. These references themselves are stored in contiguous memory locations within the list, but the objects they point to can be scattered across the memory heap.

The list itself is stored at contiguous memory locations [0x1a, 0x1b, 0x1c, 0x1d].

Each element of the list is a reference pointing to objects at 0x100, 0x200, 0x300, and 0x400.

In [2]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])
my_array = np.append(my_array, 6)
print(my_array)



[1 2 3 4 5 6]


#***Numpy***
NumPy is a Python library used for working with arrays


In [3]:
import numpy as np


In [20]:
oned_array = np.array([1,2,3,4,5])
print('1d_array:',oned_array)

1d_array: [1 2 3 4 5]


In [21]:
twod_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2d_array:',twod_array)   # 2row 4column

2d_array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
threed_array = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                        [[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print('3d_array:', threed_array)

3d_array: [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [35]:
n3 = np.zeros([3,4])
print(n3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [36]:
n3 = np.zeros([3,4],dtype = int)
print(n3)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [42]:
n4 = np.ones([3,4],dtype = int)
print(n4) #2d_array

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [47]:
n5 = np.ones([3,2,4],dtype = int)
print(n5)  #3d_array

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]]


In [53]:
#some random junk values contains while creating empty
n6 = np.empty([2,4])
print(n6)

[[4.99435141e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [62]:
# To create a array with range
n7 = np.arange(10)
print(n7)

[0 1 2 3 4 5 6 7 8 9]


In [63]:
# start,end,step(2,20,2)
n7 = np.arange(2,20,2)
print(n7)

[ 2  4  6  8 10 12 14 16 18]


***Linspace***

This used to create linearly spaced values

In [71]:
# start,end,no_of_generating_elements (1,10,5)
n8 = np.linspace(1,10,5,dtype=None)
print(n8)

[ 1.    3.25  5.5   7.75 10.  ]


In [78]:
n9 = np.full([3,2,4],5)
print(n9)

[[[5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]]]


In [81]:
n6.fill(7)
print(n6)

[[7. 7. 7. 7.]
 [7. 7. 7. 7.]]


***Accessing Elements***

In [87]:
n10 = np.array([1,2,3,4,5])
print(n10)

[1 2 3 4 5]


In [90]:
print(n10[0])
print(n10[-1])
print(n10[1:4])


1
5
[2 3 4]


In [91]:
# ([[1,2,3,4,5],[6,7,8,9,10]])
n11 = twod_array[1]
print(n11)

[ 6  7  8  9 10]


In [103]:
# ([[1,2,3,4,5],[6,7,8,9,10]])
n11 = twod_array[1,3]
print(n11)
print(twod_array[1,1:])
print(twod_array[0,:])
print(twod_array[0,:3])
print(twod_array[:,2])
print(twod_array[:,:2])

9
[ 7  8  9 10]
[1 2 3 4 5]
[1 2 3]
[3 8]
[[1 2]
 [6 7]]


In [111]:
'''([[[1,2,3],[4,5,6],[7,8,9]],
[[10,11,12],[13,14,15],[16,17,18]],
 [[19,20,21],[22,23,24],[25,26,27]]])'''


print(threed_array[1,1,1]) # matrix,row,column(1,1,1)
n12 = threed_array
print(n12)

# Modifying 14 to 20
n12[1,1,1] = 29
print(n12)

14
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 29 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


***Size and Shape***

In [115]:
print(twod_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [112]:
# To check the dimension of array
twod_array.ndim

2

In [114]:
twod_array.shape


(2, 5)

In [116]:
#Total no of element in 2d_array
twod_array.size

10

In [120]:
print(twod_array.dtype)


int64


In [121]:
#To store each element it need 8Bytes
print(twod_array.itemsize)

8


In [124]:
#To store all the elements it need this much bytes
print(twod_array.nbytes)

80
